### ISSUE TITLE
missing begin and end for preferences

### ISSUE THREAD

**Issue by dymek84** [Lixie-Labs/Emotiscope#73]
missing begin and end for preferences, in configuration file.

**Comment by connornishijima** [comment]
While I do have a 'preferences.begin("emotiscope", false);' on line 274 of configuration.h:

https://github.com/Lixie-Labs/Emotiscope/blob/80424f8a08ea87e89486e3ea7b57a54aca655604/src/configuration.h#L274

I don't have a preferences.end() anywhere in the code because it's left open for quicker saving during runtime at the expense of (probably) heap.
